### ISSUE TITLE
MI: screenshots not correct

### ISSUE THREAD

**Issue by maxerickson** [COVID19Tracking/issues#79] opened 2020-03-29 22:39 UTC
3/29 and 3/28 are not current data. I guess they changed their format yet again...

Using total - new from 3/29, the new for 3/28 are 993 cases and 19 deaths.

The totals for 3/28 are then 4650 cases and 111 deaths.

**Comment by schwartzadev** [comment] 2020-04-01 03:37
Potential duplicate of #80

**Comment by careeningspace** [comment] 2020-04-13 15:54
Hello,

We did update Michigan data after the state updated its reporting process. Please find more detailed information at #173

**Closed by careeningspace** 2020-04-13 15:54 UTC
Labels: Data source
