### ISSUE TITLE
inIcuCumulative less than inIcuCurrently starting 04/02

### ISSUE THREAD

**Issue by jcfields67** [COVID19Tracking/issues#155] opened 2020-04-03 13:03 UTC
US daily 
04/01 inIcuCurrently 3837  inIcuCumulative 4270
04/02 inIcuCurrently  4264 inIcuCumulative   541

**Comment by careeningspace** [comment] 2020-04-09 17:01
Duplicate of #132 and you can find the resolution process on that issue

**Closed by careeningspace** 2020-04-09 17:01 UTC
Labels: Data quality
