### ISSUE TITLE
On Ventilator and In ICU Cumulative vs. Currently Switched

### ISSUE THREAD

**Issue by paolinic03** [COVID19Tracking/issues#148] opened 2020-04-05 15:42 UTC
I think the figures for "On Ventilator" and "In ICU" Cumulative vs. Currently are switched unless I am looking at this incorrectly.

When looking at the totals for the latest update from April 4th,

In ICU Cumulative = 691
In ICU Currently = 5,207

On Ventilator Cumulative = 154
On Ventilator Currently = 656

How can you have more currently than you have cumulative? Please advise and if so switch these fields accordingly as soon as you can to stop folks from reporting inaccurately. Thanks.

**Comment by careeningspace** [comment] 2020-04-09 17:01
Duplicate of #132 and you can find the resolution process on that issue

**Closed by careeningspace** 2020-04-09 17:01 UTC
