### ISSUE TITLE
Utah issues reported on covid-tracking-data repo

### ISSUE THREAD

**Issue by julia326** [COVID19Tracking/issues#453] opened 2020-05-25 17:02 UTC
Someone made a PR in covid-tracking-data (https://github.com/COVID19Tracking/covid-tracking-data/pull/73) to fix some Utah data, pasting their PR description here too:

"This branch contains manually repaired data files with updates for two data events related to the state of Utah:

Hospitalization data for May 22 and 23 was somehow scraped incorrectly from the state's website. The total cumulative hospitalizations should be 660 and 676 as retrieved from https://coronavirus.utah.gov/case-counts/ on May 23 and 24 around 11:30 am Mountain.
The state's website had an outage on May 19, which caused the data for that day to be a duplicate of the May 18 data. I manually reconstructed the May 19 data from local news reporting which captured the true data reported later in the day. I also adjusted the case increment columns for May 20 to be consistent with the May 19 manual edits."

(I'm not merging PRs fixing data in covid-tracking-data, just going to link to them in issues in this repo)

**Comment by muamichali** [comment] 2020-05-25 17:26
Thanks @julia326! I am closing this since it is a dupe of Issue #450 already in this repo.

**Closed by muamichali** 2020-05-25 17:26 UTC
