### ISSUE TITLE
CA, NY & RI inicuCumulative missing

### ISSUE THREAD

**Issue by xaminmo** [COVID19Tracking/issues#154] opened 2020-04-03 14:32 UTC
On 04-02, the inicuCumulative value is missing for CA, NY and RI.  These should be the greater of the last value, or the currently in ICU, but it is probably a data import error.

This error affects the state and US, both for 04-02 and for "current".

**Comment by xaminmo** [comment] 2020-04-07 01:55
Also, Indiana just showed up missing cumulative ICU.

**Comment by careeningspace** [comment] 2020-04-09 17:02
Duplicate of #132 and you can find the resolution process on that issue

**Closed by careeningspace** 2020-04-09 17:02 UTC
Labels: Data quality
