### ISSUE TITLE
cumulative numbers less

### ISSUE THREAD

**Issue by sgb5024** [COVID19Tracking/issues#165] opened 2020-04-07 17:42 UTC
Cumulative numbers for ICU and ventilators are less than the current, should that be?

**Comment by justinbouchard** [comment] 2020-04-08 01:40
This is a big problem.  

Hospitalized Currently went from 27,675 to 39,011 on April 7th.  Why did the Hospitalized Cumulative only increase by 394 cases, from 45,168 to 45,562?

**Comment by careeningspace** [comment] 2020-04-09 16:59
Duplicate of #132 and you can find the resolution process on that issue

**Closed by careeningspace** 2020-04-09 16:59 UTC
