### ISSUE TITLE
Hospitalized Data is Unusable

### ISSUE THREAD

**Issue by TraceGroot** [COVID19Tracking/issues#162] opened 2020-04-07 06:26 UTC
For "States Historical Data", there used to only be the single field, "hospitalized".  A few days ago, two more related fields were added, "hospitalizedCurrently" and "hospitalizedCumulative".  

The problem is that data is not consistently in either "hospitalized" or "hospitalizedCumulative".  So some states have empty fields in one while other states have empty fields in the other.  In addition, some states have both of those fields empty, with the only number being in "hospitalizedCurrently".

That inconsistency makes the hospitalization data useless, as is.  You can't even set up a simple plot anymore without doing some serious massaging of the data in order to try and wrangle these three fields into something meaningful.

**Comment by muamichali** [comment] 2020-04-07 15:06
@TraceGroot Yes. This is an inherent issue with the way states are reporting the hospitalizations data. 

This was also the reason the project will no longer report overall US hospitalizations
![hospitalized](https://user-images.githubusercontent.com/1749380/78685350-a2954680-78bf-11ea-843e-6cb71c6f08c9.png)

https://twitter.com/COVID19Tracking/status/1247296434698719232

**Comment by careeningspace** [comment] 2020-04-09 16:59
Duplicate of #132 and you can find the resolution process on that issue

**Closed by careeningspace** 2020-04-09 16:59 UTC
