### ISSUE TITLE
DC on 4/15 positiveIncrease > totalTestResultsIncrease

### ISSUE THREAD

**Issue by loglow** [COVID19Tracking/issues#271] opened 2020-04-23 08:04 UTC
In the daily states data, on 4/15, in DC, we have the following impossibility:

`"positiveIncrease":139`
`"totalTestResultsIncrease":7`

and also:

`"negativeIncrease":-132`

**Comment by zachlipton** [comment] 2020-04-23 19:11
@muamichali tells me this is a duplicate of #219 

Your tool is great! Thank you!

**Closed by zachlipton** 2020-04-23 19:11 UTC
